"""rename user.password to user.password_hash

Revision ID: e7b5b30c6bb4
Revises: bfa0b792660b
Create Date: 2021-03-30 21:23:42.583909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b5b30c6bb4'
down_revision = 'bfa0b792660b'
branch_labels = None
depends_on = None


def upgrade():
    '''
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    op.add_column('user', sa.Column('password_hash', sa.String(length=60), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
    '''
    op.alter_column(
        'user', 'password',
        new_column_name='password_hash'
    )


def downgrade():
    '''
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=60), nullable=False))
    op.drop_column('user', 'password_hash')
    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=60), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
    '''
    op.alter_column(
        'user', 'password_hash',
        new_column_name='password'
    )