"""rename tables and create users.is_confirmed

Revision ID: 4b45311f7cf7
Revises: 1107175adc5b
Create Date: 2023-03-05 11:33:33.340198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b45311f7cf7'
down_revision = '1107175adc5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_language', sa.String(length=32), nullable=True),
    sa.Column('new_word', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_translation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('example')
    op.drop_index('email', table_name='user')
    op.drop_index('username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_bin', length=32), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_bin', length=128), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_bin', length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user', ['username'], unique=True)
    op.create_index('email', 'user', ['email'], unique=True)
    op.create_table('example',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created', mysql.DATETIME(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_language', mysql.VARCHAR(collation='utf8mb4_bin', length=32), nullable=True),
    sa.Column('new_word', mysql.VARCHAR(collation='utf8mb4_bin', length=128), nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_bin'), nullable=False),
    sa.Column('content_translation', mysql.TEXT(collation='utf8mb4_bin'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='example_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('examples')
    op.drop_table('users')
    # ### end Alembic commands ###
