"""introduce an `EmailAddressChange` model

Revision ID: d932ed5025ca
Revises: 8ff9b3efa93e
Create Date: 2023-05-22 04:38:50.306980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd932ed5025ca'
down_revision = '8ff9b3efa93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_address_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('old', sa.String(length=128), nullable=False),
    sa.Column('new', sa.String(length=128), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_address_change')
    # ### end Alembic commands ###
