name: workflows_run-test-suite

on:
  push:
  #   branches-ignore:
  #     - "main"

  # Runs your workflow when activity on a pull request in the workflow's repository
  # occurs. For example, if no activity types are specified, the workflow runs
  # when a pull request is opened or reopened
  # or when the head branch of the pull request is updated.
  # pull_request:
  #   branches:
  #     - main
  # pull_request_target:

  # Make it possible to run the workflow manually (from GitHub's web UI).
  workflow_dispatch:

jobs:

  run-tests-for-backend:

    runs-on: ubuntu-20.04

    outputs:
      coverage-percentage: ${{ steps.run-tests-for-b-e.outputs.coverage-percentage }}

    steps:
      - name: Check out repository onto runner
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.3'

      - name: Install Python dependencies
        run: |
          cd backend
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - id: run-tests-for-b-e
        name: Run tests
        run: |
          cd backend
          export DAYS_FOR_EMAIL_ADDRESS_CONFIRMATION=42
          export MINUTES_FOR_TOKEN_VALIDITY=42
          export MINUTES_FOR_PASSWORD_RESET=42
          coverage run \
              --source=src/ \
              --omit=venv/*,tests/* \
              -m unittest \
              discover -v \
              tests/
          coverage report > line-with-the-TOTAL.txt
          read -r -a arr <<< $(grep TOTAL line-with-the-TOTAL.txt)
          echo "coverage-percentage=${arr[3]}" >> $GITHUB_OUTPUT
  # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs

  report-coverage-for-backend:

    runs-on: ubuntu-latest

    needs: run-tests-for-backend

    steps:

      - name: Report coverage percentage
        run: |
          echo "coverage percentage:" \
            " ${{ needs.run-tests-for-backend.outputs.coverage-percentage }}"

  run-test-suite-for-frontend:

    runs-on: ubuntu-20.04

    outputs:
      coverage-percentage: ${{ steps.run-tests-for-f-e.outputs.coverage-percentage }}

    steps:
      - name: Check out repository onto runner
        uses: actions/checkout@v3

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      - name: Install Node.js dependencies
        run: |
          cd frontend
          npm install

      - id: run-tests-for-f-e
        name: Run tests 
        run: |
          cd frontend
          CI=true \
            npm test -- \
              --coverage \
              --collectCoverageFrom="./src/**" \
                > lines-with-the-coverage-across-All-files.txt
          read -r -a arr <<< $(grep "All files" lines-with-the-coverage-across-All-files.txt)
          echo "coverage-percentage=${arr[3]}" >> $GITHUB_OUTPUT
  # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs

  report-coverage-for-frontend:

    runs-on: ubuntu-latest

    needs: run-test-suite-for-frontend

    steps:

      - name: Report coverage percentage
        run: |
          echo "coverage percentage:" \
            " ${{ needs.run-test-suite-for-frontend.outputs.coverage-percentage }}%"